# 论如何做到：将特征向量按照特征值从大到小排列

In [29]:
import numpy as np
m = np.array([[1, 0.505, 0.569, 0.602, 0.621, 0.603],
[0.505, 1, 0.422, 0.467, 0.482, 0.45],
[0.569, 0.422, 1, 0.926, 0.877, 0.878],
[0.602, 0.467, 0.926, 1, 0.874, 0.894],
[0.621, 0.482, 0.877, 0.874, 1, 0.937],
[0.603, 0.45, 0.878, 0.894, 0.937, 1]])

In [30]:
evalue, evector = np.linalg.eig(m)

In [31]:
evalue

array([4.4564485 , 0.78240991, 0.45842506, 0.16883257, 0.05479622,
       0.07908774])

In [32]:
evector

array([[ 0.35079327,  0.39565321,  0.84666989,  0.05182494,  0.02561535,
        -0.01451715],
       [ 0.28620397,  0.81464058, -0.50202982,  0.02010032,  0.04236155,
        -0.01468155],
       [ 0.43997836, -0.26324462, -0.11051604,  0.50466755,  0.33278818,
        -0.59955835],
       [ 0.44688514, -0.19720294, -0.09896293,  0.47037458, -0.41567414,
         0.59797472],
       [ 0.44888063, -0.16146667, -0.06586761, -0.54823826, -0.5758624 ,
        -0.36866442],
       [ 0.44749331, -0.21345033, -0.0690664 , -0.46947138,  0.61838409,
         0.38290503]])

In [41]:
(np.array([1, 0.505, 0.569, 0.602, 0.621, 0.603]) * evector[:,0]).sum()

1.5632921556195138

In [36]:
evalue[0]*evector[:,0]

array([1.56329216, 1.27545325, 1.96074088, 1.99152059, 2.00041343,
       1.99423091])

In [38]:
m.dot(evector[:,0])

array([1.56329216, 1.27545325, 1.96074088, 1.99152059, 2.00041343,
       1.99423091])

In [7]:
idx = np.argsort(-evalue)
idx

array([0, 1, 2, 3, 5, 4])

In [8]:
es = evalue[idx]
es

array([4.4564485 , 0.78240991, 0.45842506, 0.16883257, 0.07908774,
       0.05479622])

In [12]:
#由于每一列是一个特征向量，需要调整每一列的顺序，
#而ev[idx]调整的是行的位置，因此进行两步转置
ev = evector.transpose()
ev

array([[ 0.35079327,  0.28620397,  0.43997836,  0.44688514,  0.44888063,
         0.44749331],
       [ 0.39565321,  0.81464058, -0.26324462, -0.19720294, -0.16146667,
        -0.21345033],
       [ 0.84666989, -0.50202982, -0.11051604, -0.09896293, -0.06586761,
        -0.0690664 ],
       [ 0.05182494,  0.02010032,  0.50466755,  0.47037458, -0.54823826,
        -0.46947138],
       [ 0.02561535,  0.04236155,  0.33278818, -0.41567414, -0.5758624 ,
         0.61838409],
       [-0.01451715, -0.01468155, -0.59955835,  0.59797472, -0.36866442,
         0.38290503]])

In [13]:
ev = ev[idx]
ev

array([[ 0.35079327,  0.28620397,  0.43997836,  0.44688514,  0.44888063,
         0.44749331],
       [ 0.39565321,  0.81464058, -0.26324462, -0.19720294, -0.16146667,
        -0.21345033],
       [ 0.84666989, -0.50202982, -0.11051604, -0.09896293, -0.06586761,
        -0.0690664 ],
       [ 0.05182494,  0.02010032,  0.50466755,  0.47037458, -0.54823826,
        -0.46947138],
       [-0.01451715, -0.01468155, -0.59955835,  0.59797472, -0.36866442,
         0.38290503],
       [ 0.02561535,  0.04236155,  0.33278818, -0.41567414, -0.5758624 ,
         0.61838409]])

In [14]:
ev = ev.transpose()
ev

array([[ 0.35079327,  0.39565321,  0.84666989,  0.05182494, -0.01451715,
         0.02561535],
       [ 0.28620397,  0.81464058, -0.50202982,  0.02010032, -0.01468155,
         0.04236155],
       [ 0.43997836, -0.26324462, -0.11051604,  0.50466755, -0.59955835,
         0.33278818],
       [ 0.44688514, -0.19720294, -0.09896293,  0.47037458,  0.59797472,
        -0.41567414],
       [ 0.44888063, -0.16146667, -0.06586761, -0.54823826, -0.36866442,
        -0.5758624 ],
       [ 0.44749331, -0.21345033, -0.0690664 , -0.46947138,  0.38290503,
         0.61838409]])

In [18]:
import numpy as np
import numpy.linalg as linalg
A = np.random.random((3,3))
eigenValues, eigenVectors = linalg.eig(A)


In [19]:
print(A)
print(eigenValues)
print(eigenVectors)

[[0.06038657 0.45142141 0.33832582]
 [0.5305437  0.49870353 0.54069379]
 [0.89418555 0.50619961 0.99436372]]
[ 1.66728679 -0.26456331  0.15073034]
[[-0.31231667 -0.83482169 -0.33588141]
 [-0.51202921  0.22405547 -0.60700707]
 [-0.80017772  0.50286369  0.72022642]]


In [20]:
idx = eigenValues.argsort()[::-1]
print(idx)
eigenValues = eigenValues[idx]
print(eigenValues)
eigenVectors = eigenVectors[:,idx]
print(eigenVectors)

[0 2 1]
[ 1.66728679  0.15073034 -0.26456331]
[[-0.31231667 -0.33588141 -0.83482169]
 [-0.51202921 -0.60700707  0.22405547]
 [-0.80017772  0.72022642  0.50286369]]


In [25]:

import numpy as np
class PCA(object):
    m = 0
    n = 0
    #降维所需的基向量
    base_vectors = None
    #均值归一化
    def mean_normalization(self,X):
        for j in range(self.n):
            me = np.mean(X[:,j])
            X[:,j] = X[:,j] - me
        return X
    #r为降低到的维数
    def fit(self,X,r):
        self.m = X.shape[0]
        self.n = X.shape[1]
        #均值归一化
        X = self.mean_normalization(X)
        Xt = X.T
        #协方差矩阵
        c = (1/self.m) * Xt.dot(X)
        print(c)
        #求解协方差矩阵的特征向量和特征值
        eigenvalue,featurevector=np.linalg.eig(c)
        #对特征值索引排序 从大到小
        aso = np.argsort(eigenvalue)
        indexs = aso[::-1]
        print("特征值:",eigenvalue)
        print("特征向量:",featurevector)
        print("降为",r,"维")
        eigenvalue_sum = np.sum(eigenvalue)
        self.base_vectors = []
        for i in range(r):
            print("第",indexs[i],"特征的解释率为:",(eigenvalue[indexs[i]] / eigenvalue_sum))
            self.base_vectors.append(featurevector[:,indexs[i]])#取前r个特征值大的特征向量作为基向量
        self.base_vectors = np.array(self.base_vectors)
        return
    
    def transform(self,X):
        #r*n的P乘以n*m的矩阵转置后为m*r的矩阵
        return self.base_vectors.dot(X.T).T
    def fit_transform(self,X,r):
        self.fit(X, r)
        return self.transform(X)
